### ISSUE TITLE
Is there a way to seed the template DB with fixture data?

### ISSUE THREAD

**Issue by nchelluri** [peterldowns/pgtestdb#20]
Hi, I am new to this library and enjoying it; thank you for your work on the library.

I am using it in an integration test, with [testcontainers-go](https://github.com/testcontainers/testcontainers-go) and [testify](https://github.com/stretchr/testify). My code creates a testify test suite and in the suite setup (a before hook that runs before any test cases) it will spin up a Dockerized Pg container using testcontainers and create an empty database (there is some teardown code to terminate the container as well). I am not sure how relevant this is, just offering context.

I have a test suite helper function `newDB()` which is along the lines of https://github.com/peterldowns/pgtestdb?tab=readme-ov-file#defining-a-helper: it takes a Pg URL from the running testcontainer, creates a connection to the a test DB using `testdbCfg := pgtestdb.Custom(t, cfg, m)`. `cfg` comes from using `pgx.ParseConfig()` to parse the URL of the test container and `m` is an instance of the recently-released [tern](https://github.com/jackc/tern) migrator.

This all works fine. Next I run a few functions on the test DB instance (still within `newDB()`) to seed it with fixture data. My question is: does this library offer any functionality to help seed the template DB with fixture data, so that we only have to do that once, instead of every time we call `newDB()`? An option I have thought of for our own code is to (likely programmatically) create an extension of our production migrations which includes the fixture data (which is probably doable, but a little inconvenient). But maybe an optional second migrator for seeding the template DB with fixtures on first creation or something would be easier. Or perhaps I am missing some functionality in the code (I did do a quick browse through the code as you suggested in the readme, using LSP, and could not see anything that might support this use-case). Do you have any thoughts? Thanks again.

**Comment by peterldowns** [comment]
Glad you're using and overall enjoying the library! Here's some short answers:

> My question is: does this library offer any functionality to help seed the template DB with fixture data, so that we only have to do that once, instead of every time we call newDB()?

Yes, just implement the `Migrate()` method. You can embed the `ternmigrator.TernMigrator` in a custom struct and "override" its `Migrate()` method to do some data insertion that will happen when pgtestdb creates the template database. Then, each time pgtestdb creates a new instance database from that template, the instance database will have that data.

```shell
$ tree
.
├── go.mod
├── go.sum
├── main_test.go
└── migrations
    └── 0001_initial.sql

2 directories, 4 files
```

```sql
-- file = migrations/0001_initial.sql
CREATE TABLE public.people (
    name text
);

---- create above / drop below ----

DROP TABLE public.people;
```
```go
// file = main_test.go
package main_test

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"testing"

	_ "github.com/jackc/pgx/v5/stdlib"

	"github.com/peterldowns/testy/assert"

	"github.com/peterldowns/pgtestdb"
	"github.com/peterldowns/pgtestdb/migrators/common"
	"github.com/peterldowns/pgtestdb/migrators/ternmigrator"
)

//go:embed migrations/*.sql
var exampleFS embed.FS

type MyMigrator struct {
	ternmigrator.TernMigrator
}

func (m *MyMigrator) Migrate(ctx context.Context, db *sql.DB, conf pgtestdb.Config) error {
	err := m.TernMigrator.Migrate(ctx, db, conf)
	if err != nil {
		return err
	}
	for i := 0; i < 10; i++ {
		name := fmt.Sprintf("Person %d", i)
		_, err := db.ExecContext(ctx, "INSERT INTO people VALUES ($1);", name)
		if err != nil {
			return err
		}
	}
	return nil
}

func (m *MyMigrator) Hash() (string, error) {
	wrapped, err := m.TernMigrator.Hash()
	if err != nil {
		return "", err
	}
	hash := common.NewRecursiveHash(
		common.Field("Migrations", wrapped),
		common.Field("FixtureData", `
			you have to change this string if you modify the sql statements
			executed in Migrate() or otherwise pgtestdb won't know that it
			should create a new template.
		`),
	).String()
	return hash, nil
}

func TestCustomPrepareMethod(t *testing.T) {
	t.Parallel()
	conf := pgtestdb.Config{
		DriverName: "pgx",
		User:       "postgres",
		Password:   "password",
		Host:       "localhost",
		Port:       "5433",
		Options:    "sslmode=disable",
	}
	migrator := &MyMigrator{
		*ternmigrator.New("migrations", ternmigrator.WithFS(exampleFS)),
	}
	db := pgtestdb.New(t, conf, migrator)

	var count int
	err := db.QueryRow("SELECT count(*) from people").Scan(&count)
	assert.Nil(t, err)
	assert.Equal(t, 10, count)
}
```

**Comment by nchelluri** [comment]
Ah, thanks, the example you've provided looks like exactly the sort of thing I need.

And as for:

> Just know that if you're creating a new database each time you run the suite, you're not getting the full speedup that pgtestdb can provide. The speed of pgtestdb comes from re-using template databases.

Yep, I'm aware; the note about a RAM-backed server is clear. I think when this project gets to the point where spinning up a testcontainer per run is too slow, we can consider that, but as it stands it is pretty fast. And I also did read about the testcontainers "reuse container" functionality, too, but I think that won't work for my project as I use testcontainers within GH Actions as part of CI (and the whole execution env is ephemeral/some kind of VM). (But, I think if we did end up keeping a non-GH Action execution env Pg server instance around, as you recommend, and it had a template DB, then that would obviate that issue.)

**Comment by peterldowns** [comment]
I hope the example helps! I'll probably update the docs at some point to make this clearer. Thank you again for writing in. And thanks for reading my notes about server persistence/container reuse, just wanted to make sure since some other people have been confused about it.

Please let me know if you have any further issues with the example code or with anything else. Enjoy 🫡

**Comment by nchelluri** [comment]
An update here, I was able to make this work, and was able to create an `embed.FS` from the packages containing the fixture data, then use it in a call to `common.Field()` when calling `common.NewRecursiveHash()`, so that changes to the fixture data should cause the template DB to be recreated (were it not ephemeral).

**Comment by markvincze** [comment]
I have tested using pgtestdb together with [go-testfixtures](https://github.com/go-testfixtures/testfixtures), and it seems to be working okay, so that is another option.
