### ISSUE TITLE
Support Other Connection Types (specifically a pgx.Pool)

### ISSUE THREAD

**Issue by Rshep3087** [peterldowns/pgtestdb#4]
We use sqlc, which support pgx. The generated code is is more pgx specific with the interface methods as follows

```
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}
```

So creating a test db doesn't work since a database/sql DB does not satisfy the interface.

We worked around this by using https://github.com/jackc/pgx/blob/master/stdlib/sql.go which can create a database/sql DB from a pool for our production code and then use the pgtestdb DB for tests. But it would be nice if we could find a way to support the pgx.Conn and pgx.Pool types. pgxpool implements a nearly identical interface to pgx connections.

**Comment by peterldowns** [comment]
Thank you very much for the suggestion! This should be resolved as of [11a64cc](https://github.com/peterldowns/pgtestdb/commit/11a64ccdbb8b75985619d545401dfec44fdc2c34) by the `pgtestdb.Custom` method, now documented here:

* https://github.com/peterldowns/pgtestdb#pgtestdbcustom
* https://github.com/peterldowns/pgtestdb#how-do-i-connect-to-the-test-databases-through-pgx--pgxpool-instead-of-using-the-sqldb-interface

Please let me know how this works, or if this is insufficient for some reason.
